-- Blog CMS: move posts from hardcoded files to data so they can be
-- generated by the AI cron and published by the owner without a deploy.

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug             text UNIQUE NOT NULL,
  status           text NOT NULL DEFAULT 'pending_review',  -- draft|pending_review|published|discarded
  category         text,
  hero_image       text,          -- Supabase Storage public URL
  hero_credit      text,          -- stock photographer (Pexels)
  reading_minutes  int  DEFAULT 4,
  title            jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {de,en,fr,it}
  summary          jsonb NOT NULL DEFAULT '{}'::jsonb,
  meta_description jsonb NOT NULL DEFAULT '{}'::jsonb,
  body             jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {de:[{heading,body}],en:[...],...}
  internal_links   text[] DEFAULT '{}',
  review_token     text,
  source           text DEFAULT 'manual',  -- manual|ai
  created_at       timestamptz NOT NULL DEFAULT now(),
  published_at     timestamptz
);

CREATE INDEX IF NOT EXISTS blog_posts_status_idx ON public.blog_posts (status, published_at DESC);

CREATE TABLE IF NOT EXISTS public.blog_topics (
  id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword   text NOT NULL,
  brief     text,
  status    text NOT NULL DEFAULT 'queued',  -- queued|used
  sort      int  DEFAULT 0,
  used_at   timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Both tables are server-only (accessed via service_role). Lock out anon.
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_topics ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.blog_posts FROM anon, authenticated;
REVOKE ALL ON public.blog_topics FROM anon, authenticated;

COMMENT ON TABLE public.blog_posts IS 'Blog posts (manual + AI-generated). Rendered via service_role on the server.';
COMMENT ON TABLE public.blog_topics IS 'Predefined topic queue for the AI blog generator.';
